In [ ]:
import numpy as np

# Broadcasting

1. ```
  a = np.array([[1, 1, 2], [3, 2, 1], [1, 9, 1]])
  b = np.array([[1], [2], [3]])
  ```
  `a.shape` = (3, 3), `b.shape` = (3, 1)

  Rule 1: `a` and `b` already have the same number of dimensions.

  Rule 2: `a.shape` = (3, 3), `b.shape` = (3, 3)

In [ ]:
a = np.array([[1, 1, 2], [3, 2, 1], [1, 9, 1]])
b = np.array([[1], [2], [3]])
print((a+b).shape)
a+b

(3, 3)


array([[ 2,  2,  3],
       [ 5,  4,  3],
       [ 4, 12,  4]])

2. ```
  a = np.array([[1, 1, 2], [3, 2, 1], [1, 9, 1]])
  b = np.array([[1], [2], [3]])
  ```
  `a.shape` = (2, 2, 2), `b.shape` = (2,)

  Rule 1: `a.shape` = (2, 2, 2), `b.shape` = (1, 1, 2)

  Rule 2: `a.shape` = (2, 2, 2), `b.shape` = (2, 2, 2)

In [ ]:
a = np.array([[[1, 2], [3, 1]], [[8, 7], [9, 1]]])
b = np.array([10, 11])
print((a+b).shape)
a+b

(2, 2, 2)


array([[[11, 13],
        [13, 12]],

       [[18, 18],
        [19, 12]]])

3. ```
  a = np.array([1, 2, 3])
  b = np.array([[10], [11], [12]])
  ```
  `a.shape` = (3,), `b.shape` = (3, 1)

  Rule 1: `a.shape` = (1, 3), `b.shape` = (3, 1)

  Rule 2: `a.shape` = (3, 3), `b.shape` = (3, 3)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[10], [11], [12]])
print((a+b).shape)
a+b

(3, 3)


array([[11, 12, 13],
       [12, 13, 14],
       [13, 14, 15]])

4. ```
  a = np.array([[[1, 2], [3, 1]], [[8, 7], [9, 1]]])
  b = np.array([10, 11, 12, 13])
  ```
  `a.shape` = (2, 2, 2), `b.shape` = (4,)

  Rule 1: `a.shape` = (2, 2, 2), `b.shape` = (1, 1, 4)

  Rule 2: `a.shape` = (2, 2, 2), `b.shape` = (2, 2, 4)

  Rule 3: `a` and `b` do not match in the last dimension (`a`=2, `b`=4). They cannot be added.

In [ ]:
a = np.array([[[1, 2], [3, 1]], [[8, 7], [9, 1]]])
b = np.array([10, 11, 12, 13])
a+b

ValueError: operands could not be broadcast together with shapes (2,2,2) (4,) 

5. ```
  a = np.array([[[[1]]], [[[2]]]])
  b = np.array([3, 4])
  ```
  `a.shape` = (2, 1, 1, 1), `b.shape` = (2,)

  Rule 1: `a.shape` = (2, 1, 1, 1), `b.shape` = (1, 1, 1, 2)

  Rule 2: `a.shape` = (2, 1, 1, 2), `b.shape` = (2, 1, 1, 2)

In [ ]:
a = np.array([[[[1]]], [[[2]]]])
b = np.array([3, 4])
print((a+b).shape)
a+b

(2, 1, 1, 2)


array([[[[4, 5]]],


       [[[5, 6]]]])

#Solar

In [ ]:
# Load the solar.csv data. Note that the file `solar.csv` must be uploaded
# into Colab session storage before this cell can be run.
solar_data = np.loadtxt('solar.csv')

In [ ]:
# 1. How many watts were generated all year?
np.sum(solar_data)

218010.26201750195

In [ ]:
# 2. What is the highest number of watts produced by the solar panels? The lowest?
print("Highest:", np.max(solar_data))
print("Lowest:", np.min(solar_data))

Highest: 450.23976606026287
Lowest: 0.0


In [ ]:
# 3. What is the highest number of watts in the morning, afternoon, and evening? The lowest?
print("Highest in the morning, afternoon, and evening:", np.max(solar_data, axis=0))
print("Lowest in the morning, afternoon, and evening:", np.min(solar_data, axis=0))

Highest in the morning, afternoon, and evening: [446.40434207 450.23976606 247.01509894]
Lowest in the morning, afternoon, and evening: [166.23303073   0.           0.        ]


In [ ]:
# 4. What is the average number of watts generated in January?
# Some students approached this problem differently, and I accepted both variants.

# Approach 1: Average all readings across January
print("Average wattage across all readings in January:", np.mean(solar_data[:31]))

# Approach 2: Average across the daily energy production totals of January
print("Average daily production in January:", np.mean(np.sum(solar_data[:31], axis=1)))

Average wattage across all readings in January: 202.55189316344854
Average daily production in January: 607.6556794903456


In [ ]:
# 5. What is the average number of watts generated on January afternoons?
print("Average afternoon wattage in January:", np.mean(solar_data[:31, 1]))

Average afternoon wattage in January: 215.93478827333328


In [ ]:
# 6. How many readings had less than 50 watts?
print("Number of readings with less than 50 watts:", np.sum(solar_data < 50))

Number of readings with less than 50 watts: 92


In [ ]:
# 7. Of the readings with less than 50 watts, what was the highest amount?
print("Highest reading under 50 watts:", np.max(solar_data[solar_data < 50]))

Highest reading under 50 watts: 49.317967494803355


In [ ]:
# 8. How many evenings had less than 50 watts?
print("Number of evenings with less than 50 watts:", np.sum(solar_data[:,2] < 50))

Number of evenings with less than 50 watts: 62


In [ ]:
# 9. How many days had less than 500 watts total?
print("Number of days with less than 500 watts total:", np.sum(np.sum(solar_data, axis=1) < 500))

Number of days with less than 500 watts total: 89


In [ ]:
# 10. Accidentally ommitted from the homework

In [ ]:
# Bonus: Which direction are the solar panels most likely facing, and why?
# If we look at the wattage produced at each of the 3 time periods, we see that
# on average, the most wattage is produced in the morning. This suggests the
# solar panels are probably facing east, where they receive the most direct
# light when the sun rises.
print("Average wattage for mornings, afternoons, and evenings:", np.mean(solar_data, axis=0))

Average wattage for mornings, afternoons, and evenings: [300.38834891 198.39523217  98.50480801]
