## Broadcasting

### Rules of Broadcosting


* Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
* Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
* Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.



### Problem 1.1

The arrays can be added together.

Rules application:

Starts as a.shape = (3, 3)  b.shape= (3, 1)

a and b have the same number of dimensions.
1.Same, dimensions number. Doesn't apply Rule 1


a  and b dont match their shape. Thus, b (the array 1 in the dimension unmatched) is stretched to match a.
2. Apply rule 2 to b: a.shape = (3, 3) b.shape(3, 3)


In [ ]:
import numpy as np
import pandas as pd

a = np.array([
  [ 1 , 1 , 2 ] ,
  [ 3 , 2 , 1 ] ,
  [ 1 , 9 , 1 ]
])

b = np.array([
  [ 1 ],
  [ 2 ],
  [ 3 ]
])

print(a.shape, b.shape)
a + b


(3, 3) (3, 1)


array([[ 2,  2,  3],
       [ 5,  4,  3],
       [ 4, 12,  4]])


### Problem 1.2

The arrays can be added together.

A.shape = (2, 2, 2), b.shape = (2,)

Rules application:

1. Apply Rule 1 to b: a.shape = (2,2,2), b.shape = (2, 1, 1)


don't have the same number of dimensions therefore, the one with fewest dimensions (b) is padded with ones.

b becomes:

```
[[[10, 11]]]
```

2. Apply Rule 2 to b: a.shape(2, 2, 2), b.shape(2, 2, 2)

b becomes
```
[
[
  [10, 11],
  [10, 11]

],
[
  [10, 11],
  [10, 11]
]

]
```






In [ ]:
a = [[[1, 2], [3, 1]],
     [[8, 7], [9, 1]]]

b = [10, 11]

print(np.array(a).shape, np.array(b).shape)
np.array(a) + np.array(b)

(2, 2, 2) (2,)


array([[[11, 13],
        [13, 12]],

       [[18, 18],
        [19, 12]]])


### Problem 1.3

The arrays can be added together.

Rules application:

Starts with a.shape = (3, ) b.shape = (3, 1)
1. Apply rule 1 to a: a.shape = (1, 3) b.shape = (3, 1)

a doesn't match number of dimensions. Thus, a (being the smallest dimension wise) is padded to become

```
[
  [1, 2, 3]
]
```

2. Apply rule 2 to a and b: a.shape = (3, 3) b.shape= (3, 3)

Dimension size doesnt match, thus,

a becomes:

```
[
  [1, 2, 3],
  [1, 2, 3],
  [1, 2, 3]
]
```

b becomes:

```
[
  [10, 10, 10],
  [11, 11, 11],
  [12, 12, 12]
]
```



In [ ]:
a = [1, 2, 3]
b = [
    [10],
    [11],
    [12]
]


print(np.array(a).shape, np.array(b).shape)
np.array(a) + np.array(b)

(3,) (3, 1)


array([[11, 12, 13],
       [12, 13, 14],
       [13, 14, 15]])



### Problem 1.4

The arrays cannot be added together.

Rules Steps:

Starts with a.shape = (2, 2, 2) b.shape = (4,)

1. Apply Rule 1 to b: a.shape = (2, 2, 2), b.shape = (4, 1, 1)

a and b dont match dimension count, therefore, b, which is the one with fewer dimensions, gets padded and becomes:

```
[[10, 11, 12, 13]]
```

2. Apply rule 2 to b: a.shape = (2, 2, 2) b.shape = (4, 4, 4)

a and b dont match the shape, thus, b gets stretched.


`a` doesnt have array with 1 size, thus doesn't stretch.

`b` becomes:

```
[
  [[10, 11, 12, 13],  [10, 11, 12, 13]],
  [[10, 11, 12, 13],  [10, 11, 12, 13]]
]
```

3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised. **Which occurs**


In [ ]:

a = [
 [[1, 2], [3, 1]],
 [[8, 7], [9, 1]]
]

b = [10, 11, 12, 13]

print(np.array(a).shape, np.array(b).shape)
np.array(a) + np.array(b)

(2, 2, 2) (4,)


ValueError: operands could not be broadcast together with shapes (2,2,2) (4,) 

### Problem 1.5

The arrays cannot be added together.

Rule Steps:
Starts with a = (2, 1, 1, 1) b= (2,)

1. Apply rule 1 to b: a.shape = (2, 1, 1, 1), b.shape = (2, 1, 1, 1)

`a` and `b` dont match, dimension `b`.` `b` Being the smallest dimension count, is padded into:

```
[
[[[[3, 4]]]
]
```

2. Apply rule 2 to a and b: a.shape = (2, 2, 2, 2), b.shape = (2, 2, 2, 2)

`a` Is stretched to match `b`

`a` Becomes:

```
[
    [[[ 1, 1 ]]] ,
    [[[ 2, 2 ]]]
]

```
`b` becomes:

```
[
  [[[[3, 4]]],
  [[[[3, 4]]]
]
```


In [ ]:
a =  [
    [[[ 1 ]]] ,
    [[[ 2 ]]]
]

b = [3, 4]

print(np.array(a).shape, np.array(b).shape)

np.array(a) + np.array(b)

(2, 1, 1, 1) (2,)


array([[[[4, 5]]],


       [[[5, 6]]]])

In [ ]:
# prompt: Load data from solar.csv to numpy array

import numpy as np
SOLAR_PATH = 'solar.csv'
# SOLAR_PATH = '/content/drive/MyDrive/College/CISC 3225 Data Tools/solar.csv'
solar_data = np.loadtxt(SOLAR_PATH, delimiter=',', unpack=True, dtype=float)
solar_data

array([[277.97178749, 276.79002882, 196.02083865, ..., 281.2492984 ,
        308.79714745, 255.70751034],
       [290.87848694,   0.        , 126.81410304, ..., 145.13885509,
        109.84031278, 122.4024413 ],
       [ 16.27913217,  92.19335012, 127.24963504, ...,  68.75927169,
        135.8464653 , 117.49570871]])

In [ ]:
# 1. How many watts were generated all year?

total_watts_tracked = solar_data.sum()
print(f'The total wats generated all year is {total_watts_tracked}')

The total wats generated all year is 218010.26201750195


In [ ]:
# 2. What is the highest number of watts produced by the solar panels? The lowest?

maxwatts = solar_data.sum()
minwatts = solar_data.min()

print(f"The max watts was {maxwatts} the min watts was {minwatts}")

The max watts was 218010.26201750195 the min watts was 0.0


In [ ]:

# Slicing Example
# This retursn the first date's data
print(solar_data[: ,0])

# This returns The Mornings data for all 365 days.
print(solar_data[0, :])
print(solar_data[0, :].size)

[277.97178749 290.87848694  16.27913217]
[277.97178749 276.79002882 196.02083865 298.0649882  257.07155815
 323.3315445  354.72384951 305.53166165 247.08196228 250.0727405
 360.41314527 320.67253413 297.39000994 281.8230464  296.57061378
 280.60487936 281.21314398 291.57324724 254.92957753 266.46231132
 345.83453839 281.95477835 226.33411278 287.58506279 349.02474298
 314.70930858 345.89214387 298.16135496 402.49143062 244.26786802
 331.79256436 219.33022089 292.22285761 334.93237956 193.48329016
 338.72024457 276.17043266 339.38620293 288.21911655 300.75926327
 281.96247581 328.32448015 397.46910172 362.87152189 369.84014752
 296.44084198 312.9437752  269.5589366  197.90647833 240.92915937
 303.45432347 411.89313156 344.19742053 234.02224665 288.34534299
 300.7235094  260.14211589 305.65574146 257.03789698 270.00389702
 237.22595068 190.74448256 205.79473695 279.45882213 262.2269118
 270.22961005 270.90582318 381.01098468 415.11591147 323.13891637
 349.24958995 256.40699221 375.297894

In [ ]:
# 3. What is the highest number of watts in the morning, afternoon, and evening? The lowest?

high_morning = solar_data[0, :].max()
low_morning = solar_data[0, :].min()

high_afternoon = solar_data[1, :].max()
low_afternoon = solar_data[1, :].min()

high_evening = solar_data[2, :].max()
low_evening = solar_data[2, :].min()

print(f'Highest in the morning {high_morning}; Lowest in the morning {low_morning}')

print(f'Highest in the afternoon {high_afternoon}; Lowest in the afternoon {low_afternoon}')

print(f'Highest in the evening {high_evening}; lowest in the evening {low_evening}')


Highest in the morning 446.4043420712958; Lowest in the morning 166.23303072555183
Highest in the afternoon 450.23976606026287; Lowest in the afternoon 0.0
Highest in the evening 247.0150989425381; lowest in the evening 0.0


In [ ]:
# 4. What is the average number of watts generated in January (i.e., over all readings in the first 31 days)?

print('Expected to be 3x31 data points.', solar_data[:, :31].size)

print('Average Watts generated in January is', solar_data.mean())


Expected to be 3x31 data points. 93
Average Watts generated in January is 199.0961296963488


In [ ]:
# 5. What is the average number of watts generated on January afternoons (i.e, afternoons for the first 31 days)?


print('Average Watts generated in January is', solar_data[:, 31].mean())


Average Watts generated in January is 164.02476587667297


In [ ]:
# 6. How many readings had less than 50 watts?

print('Readings less than 50 Watts')
# Using Boolean Masking
print(solar_data[solar_data < 50])

print('====' * 25)

print('Count of readings with less than 50 watts is', solar_data[solar_data < 50].size)


Readings less than 50 Watts
[ 0.          0.          0.          4.09148506 12.19999701 14.45621789
 45.37754339 24.44543584  0.          0.          0.          0.
 18.01491844  0.          0.          0.         12.56182753 34.7829153
 47.71191015  0.         29.48418713 21.86929189 35.93366083 22.17300337
  0.         28.56012225 28.80883646  0.         18.60087398 49.31796749
 16.27913217 45.84034965 22.97553758 41.7863011  46.21146056 26.24018571
 28.40806268 25.77362073  0.         20.93617433  8.71818903 32.43833018
 44.18550817 37.84127142 21.36222526  0.          0.         11.26057002
 40.14334792 26.97432177 41.48968367  0.          1.84339645  0.
  6.94242372 13.09344703  6.86414807  0.          0.         48.77761773
  0.          4.63597121  2.75527944 34.77675643 31.20393819 26.99315168
 34.24662036  3.50133252 41.99697577 35.06228729  4.7110161  29.24230955
 34.91838034 42.52749499  0.         34.73850948 10.19063849 41.64785623
 27.5184292  35.35715723 44.35177846 22.

In [ ]:
# 7. Of the readings with less than 50 watts, what was the highest amount

print('Among the readings with less than 50 Watts, the highest amount was', solar_data[solar_data < 50].max())




Among the readings with less than 50 Watts, the highest amount was 49.317967494803355


In [ ]:
# 8. How many evening had less than 50 watts?


mornings = solar_data[0][:]

print('mornings with less than 50 watts:', mornings[mornings < 50].size)


afternoon = solar_data[1][:]

print('afternoon with less than 50 watts:', afternoon[afternoon < 50].size)

evenings = solar_data[2][:]

print('Evenings with less than 50 watts:', evenings[evenings < 50].size)

# Great they add up to 92!

mornings with less than 50 watts: 0
afternoon with less than 50 watts: 30
Evenings with less than 50 watts: 62


In [ ]:
# 9. How many days had less than 500 watts total?

date_sum_series = solar_data.sum(axis = 0)
print(date_sum_series[:10])
print(date_sum_series.size) # Expected to be 365 sums

print('days with less than 500 wats are', date_sum_series[date_sum_series < 500].size)

# print('==='*19)
# print(date_sum_series)


[585.1294066  368.98337894 450.08457673 554.34535032 583.01645608
 763.04941888 613.83940043 495.07496892 785.66097354 444.7628872 ]
365
days with less than 500 wats are 89


#### 10. In what direction are the solar panels facing?

According to this video short ^1 and some logic, knowing that the sun rises in the east and set in the west. East Facing produces more energy in the mornings. While West Facing produce more energy during the afternoons. The best direction to go is South ^2 and the worst is the North ^2

^1 https://www.youtube.com/watch?v=aAUqAYssXY0&ab_channel=SolarQuotes

![](https://www.solarpoweraustralia.com.au/wp-content/uploads/2019/01/image.png)

> From https://www.solarpoweraustralia.com.au/east-and-west-facing-solar-panels

In [ ]:
## Comparing the morning, afternoon, evening average

print('='*10, 'Morning, Afternoon, Evening', '='*10)
print(solar_data.mean(axis=1))


========== Morning, Afternoon, Evening ==========
[300.38834891 198.39523217  98.50480801]


Therefore since, on average, more energy is produced in the mornings. The Solar panel is likely facing **East**.